### ISSUE TITLE
cargo install

### ISSUE THREAD

**Issue by robbym** [SpaceManiac/SpacemanDMM#14]
Downloading and installing via `cargo install dmm-tools` would be nice.

**Comment by robbym** [comment]
Oh, it works via `cargo install --git https://github.com/SpaceManiac/SpacemanDMM cli`

**Comment by SpaceManiac** [comment]
Providing non-git `cargo install` would involve versioning all the component crates on Cargo which I'm not ready to do yet. I need to update the install instructions in the readme anyways though, might as well add that command.

**Comment by Cyberboss** [comment]
... Why didn't you tell me aboot dis...

**Comment by SpaceManiac** [comment]
Instructions have been added to the README as of 52790ebbb9f71808e5c2f1a29a2af61d7362133e. Versioning all the component crates is at minimum a long way off and may never happen.

Cloning the repo is still recommended if you intend to keep up to date, because `cargo install` does not cache dependencies.
