### ISSUE TITLE
Non-useful linter output for an unknown error

### ISSUE THREAD

**Issue by gbasood** [SpaceManiac/SpacemanDMM#15]
```json
{
	"resource": "/G:/Git/vgstation/(unknown)",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "undefined",
	"severity": 8,
	"message": "got '__EOF__', expected one of: unary operator, term",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

Specifically the problem here is that, since I don't know where the linter was when it threw this error, I have no idea how to fix the problem.

Possibly related:
```json
{
	"resource": "/G:/Git/vgstation/code/game/machinery/doors/firedoor.dm",
	"owner": "_generated_diagnostic_collection_name_#7",
	"code": "undefined",
	"severity": 8,
	"message": "got '1', expected one of: identifier, '/', '[', contents, newline, '__EOF__', '/', identifier",
	"startLineNumber": 1,
	"startColumn": 12,
	"endLineNumber": 1,
	"endColumn": 12
}
```
This error is for a line that is valid when removed from this codebase and linted on its own:
`/var/const/OPEN = 1`

**Comment by SpaceManiac** [comment]
On the second one, you have a `#define OPEN 1` or something similar. So this line is expanded to `/var/const/1 = 1`. DreamMaker silently ignores this entire line for some reason, but my parser doesn't handle it, because it's nonsense. It's possible the first one is fallout of that, but it's unfortunate it isn't giving a location.

**Comment by SpaceManiac** [comment]
The unknown-location error appears independently of the other; I'll look into it when I can.

**Comment by SpaceManiac** [comment]
Here is the problematic source:

https://github.com/vgstation-coders/vgstation13/blob/3fad58ff2cc80d8390cccea326e0ef26dfb6e837/code/world.dm#L65-L71

As you can see, the `#elif` has no condition. When the preprocessor invoked the parser, it failed to pass location information because it passed no tokens. This will be addressed in the next release, and the error message will include location information.
