### ISSUE TITLE
Error: Spawn UNKNOWN

### ISSUE THREAD

**Issue by stanalbatross** [SpaceManiac/SpacemanDMM#300]
![image](https://user-images.githubusercontent.com/66756236/143502521-56e10e84-edae-422e-9d72-51391c45031b.png)

No idea what this message is about (other than the error part), has been happening every time I try to run the extension since Wednesday this week. Reverting to older versions hasn't fixed it either.

**Comment by SpaceManiac** [comment]
This is caused by weirdness downloading the language server `.exe`. Usually there's a message in the interface about what went wrong, but if there's corruption, you can delete `C:\Users\YOURNAME\.vscode\extensions\platymuus.dm-langclient-VERSION\bin\` to force it to retry. Could be related to #298 which I've just published an update with a workaround for. Can you update the extension and try again?

**Comment by EldritchBaguette** [comment]
Might not be related to 298; this error happens if you provide an inappropriate path for the langserver. If anyone's having the issue, ensure the path in extension settings is blank or points to the file in the extensions folder.
