### ISSUE TITLE
Editor: Can't use ctrl mouse movement on macOS

### ISSUE THREAD

**Issue by PJB3005** [SpaceManiac/SpacemanDMM#33]
On macOS, the functions of control and the super key (Command) are reversed in most cases.

Control+mouse wheel is bound for an OS-level zoom function, which conflicts with the horizontal movement of the editor.

Most of the other control-bound keys do work though.

Also, shift-mouse wheel seems to be broken too but I'm not sure what's up with that.

**Comment by SpaceManiac** [comment]
It should be easy to simply replace checks for Ctrl with checks for Command when on macOS. I'm not so familiar with macOS conventions; would this make sense?

Shift+mouse wheel basically just scrolls "really fast"... it's not particularly usable even when it is working. I assume just wheel (no modifiers) works fine?

**Comment by PJB3005** [comment]
> I'm not so familiar with macOS conventions; would this make sense?

Pretty much, yeah. There's a few odd binds using control but 99% of the usual ones like ctrl-o are just cmd-o instead.

> I assume just wheel (no modifiers) works fine?

It does indeed.

**Comment by SpaceManiac** [comment]
Attempt made in f759e06fbd3e4db2998ef1d76d211c415a01d77a. Let me know how it tests.

**Comment by SpaceManiac** [comment]
For the record, the mentioned commit ran up against the `key_super()` method being missing. This was fixed in imgui-rs v0.0.21 by https://github.com/Gekkio/imgui-rs/pull/160.

Unfortunately glutin does not appear to actually generate `LWin` or `RWin` virtual keycodes on any platform. The scancodes which correspond to the command key on macOS the will need to be observed and implemented in `support.rs`.

**Comment by SpaceManiac** [comment]
PJB reports that their system actually does generate the `RWin` virtual keycode at least. Since it's irrelevant on Windows/Linux, this can be considered fixed.
