### ISSUE TITLE
Server crashing for whatever reason

### ISSUE THREAD

**Issue by Valiant1st** [SpaceManiac/SpacemanDMM#396]
I'm new to VSC and DM. And have been using the language client since I was messing around with things not until like around early june it started to crashed saying things like.
'The DreamMaker Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted."
"[Info  - 14:39:13] Connection to server got closed. Server will restart.
[Info  - 14:39:13] Connection to server got closed. Server will restart.
[Info  - 14:39:13] Connection to server got closed. Server will restart.
[Info  - 14:39:13] Connection to server got closed. Server will restart.
[Error - 14:39:13] Connection to server got closed. Server will not be restarted."
etc. Not sure what's wrong, I'm just looking for a fix to run DM on VSC.

**Comment by MrStonedOne** [comment]
Can confirm this happens for me on 1.9 langserver exe release, but not the 1.8 langserv exe release. (as well as the auto-downloaded file in the extension's folder)

Manually running it gives "this application could not start correctly (0x00000005)" with no useful logs in event viewer. something must have changed with the build or versions. are you using latest rust? maybe its a thing that could happen to 1.9 too.

# Workaround:
1. Grab `dm-langserver.exe` here: https://github.com/SpaceManiac/SpacemanDMM/releases/tag/suite-1.8  
2. Put it some where clever, you can't move it after.
3. Shift + Right click on it, and click `copy as path`
4. go vscode -> extensions(looks like a tetris block) -> dreammaker language client -> gear -> extension settings:  
    * dreammaker: auto update: **uncheck**
    * dreammaker: langserver path -> Paste the path you copied in step 3 -> **Remove the double quotes** (vscode adds its own)

**Comment by SpaceManiac** [comment]
MSO's info makes me think that SpacemanDMM 1.9 no longer works correctly on Windows 7. I keep rustc up to date and they [dropped tier 1 support for Win7](https://github.com/rust-lang/compiler-team/issues/651) earlier this year due to lack of CI resources for the platform. If you need SpacemanDMM to function on Win7, I suggest compiling it yourself, either on rustc 1.77 or against the [volunteer Win7 target](https://doc.rust-lang.org/rustc/platform-support/win7-windows-msvc.html).
